# 1.Numpy.isscalar()



In [4]:
# It is a logic function in NumPy that returns true if the type of input num is scalar.If not returns false.

import numpy as np
np.isscalar(False) # False is boolean which is also a scalar type

True

# 2.Numpy.iscomplex()

In [6]:
#This a logic function in NumPy which return a bool array, where True if input element is complex.If not returns false.

# input has a non-zero imaginary part.

import numpy as np
np.iscomplex([2+0j,2+2j,3,5,1+3j])

array([False,  True, False, False,  True])

# 3.Numpy.array_equal()

In [8]:
#This a logic function in NumPy which return true only when the given specific arrays are equal.If not returns false.

import numpy as np
np.array_equal([2,3],[2,3])

True

In [9]:
np.array_equal([1,2,3],[4,7])

False

# 4.Numpy.less_equal()

In [11]:
# This a logic function in NumPy which return true when X1(first array) should be less than or equal to X2 i.e X1=<X2

import numpy as np
x1 = [1,4,7]
x2 = [2,8,9]
np.less_equal(x1,x2)


array([ True,  True,  True])

# 5.Numpy.multiple()

In [14]:
# This is a mathematical function which is used to multiplication of two arrays of same size.

import numpy as np

a1 = ([4,7,5],[2,6,9])
a2 = ([1,5,3],[4,0,9])
np.multiply(a1,a2)

array([[ 4, 35, 15],
       [ 8,  0, 81]])

# 6. Numpy.lcm()

In [17]:
# This is a mathematical function which is used to find least common multiple (LCM) of two numbers or arrays
import numpy as np
var = [4,12,5]
np.lcm.reduce(var) # In this function reduce() is used for reducing the array and giving output as a single final value.



60

# 7.Numpy.gcd()

In [19]:
# This is a mathematical function which is used to find greatest common Divisor (GCD) of two numbers or arrays.
import numpy as np
tmp = [40,56,84,12,24]
np.gcd.reduce(tmp) # In this function reduce() is used for reducing the array and giving output as a single final value.







4

# 8.Numpy.random.power()

In [22]:
# This is a statistical function, which  gives the random samples from power distribution and return the random samples. 
import numpy as np
a = 5. # shape
samples = 100
s = np.random.power(a, samples)
s


array([0.80968364, 0.88611822, 0.79997294, 0.68737372, 0.94752636,
       0.95555218, 0.96029216, 0.9442932 , 0.71584957, 0.8336254 ,
       0.85169439, 0.7918272 , 0.93621331, 0.89690846, 0.42541995,
       0.81110882, 0.83945181, 0.82093623, 0.80495122, 0.76998272,
       0.90285267, 0.94744641, 0.90470742, 0.97758965, 0.51400929,
       0.89854627, 0.71481737, 0.76305096, 0.73112894, 0.73574446,
       0.683358  , 0.32787877, 0.72886404, 0.91625949, 0.83997007,
       0.73082722, 0.63197426, 0.9078239 , 0.94145671, 0.48736588,
       0.80101677, 0.81650007, 0.40122248, 0.95032539, 0.64726921,
       0.84695239, 0.81240559, 0.92415181, 0.64723816, 0.9908233 ,
       0.94859715, 0.74712467, 0.91814205, 0.87157294, 0.97591985,
       0.98055183, 0.9063718 , 0.9535028 , 0.52225988, 0.92688358,
       0.98950527, 0.89514971, 0.92558106, 0.99291706, 0.83257632,
       0.92099329, 0.74445432, 0.95507128, 0.97121634, 0.85544729,
       0.62767909, 0.79325429, 0.85591359, 0.97822467, 0.71774

# 9.Numpy.logaddexp()

In [24]:
# This is a statistical function used to calculate Logarithm of the sum of exponentiations of the inputs.
import numpy as np
b1 = [4,7,5]
b2 = [3,6,9]
np.logaddexp(b1,b2)

array([4.31326169, 7.31326169, 9.01814993])

# 10.Numpy.pad()

In [27]:
#This is a statistical function used to pad the Numpy arrays. (pad:  a process in which the array is altered with some values at the beginning and end)
import numpy as np
arr = [3,6,7,2,8]
np.pad(arr, (4,3), 'constant',constant_values=(5,4))

array([5, 5, 5, 5, 3, 6, 7, 2, 8, 4, 4, 4])